# Generated by Django 2.2 on 2019-12-20 11:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_delete_language'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='tags',
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name='article',
            name='language',
            field=models.ForeignKey(default='other', on_delete=django.db.models.deletion.CASCADE, to='blog.Language'),
        ),
    ]
