# Generated by Django 2.2 on 2019-12-20 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20191220_1455'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='language',
        ),
    ]
